---
- name: fetch a file from controlled nodes
  hosts: centos
  become: false
  gather_facts: false

  tasks:
    - name: checksum on controoled node
      stat:
        path: /tmp/test_touch.txt
      register: remote_file
    
    - name: check if the file exists
      stat:
        path: /home/nikhil/test_touch.txt
      register: local_file
      delegate_to: localhost

    - name: fetching test_touch file
      fetch:
        src: /tmp/test_touch.txt
        dest: /home/nikhil/
        flat: yes  
      when: remote_file.stat.checksum != local_file.stat.checksum
      register: exs

    - name: Debug stat output
      debug:
        var: exs

