---
- name: fetch a file from controlled nodes
  hosts: centos
  become: false
  gather_facts: false

  tasks:
   - name: fetching test_touch file
     fetch:
       src: /tmp/test_touch.txt
       dest: /home/nikhil/
       flat: yes  
